version: '3.7'
services:
  zwavejs2mqtt-build-base:
    image: zwavejs/zwavejs2mqtt-build-base:${BUILD_BASE_IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile.build-base
      args:
        - "NODE_IMAGE_TAG=${NODE_IMAGE_TAG:-12.20.1-alpine}"
  zwavejs2mqtt-build:
    image: zwavejs/zwavejs2mqtt-build:${BUILD_IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile.build
      args:
        - "BUILD_BASE_IMAGE_TAG=${BUILD_BASE_IMAGE_TAG:-latest}"
    depends_on:
      - zwavejs2mqtt-build-base
  zwavejs2mqtt-runtime-base:
    image: zwavejs/zwavejs2mqtt-runtime-base:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.runtime-base
      args:
        - "NODE_IMAGE_TAG=${NODE_IMAGE_TAG:-12.20.1-alpine}"
  zwavejs2mqtt-runtime:
    image: zwavejs/zwavejs2mqtt-runtime:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.runtime
      args:
        - "BUILD_IMAGE_TAG=${BUILD_IMAGE_TAG:-latest}"
        - "RUNTIME_BASE_IMAGE_TAG=${RUNTIME_BASE_IMAGE_TAG:-latest}"
    depends_on:
      - zwavejs2mqtt-build
      - zwavejs2mqtt-runtime-base
