name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1
      # - uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Login to dockerhub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: zwavejs/zwavejs2mqtt
          tag-sha: true
          tag-latest: true
          tag-semver: |
            {{version}}
          tag-custom: ${{ github.ref == 'refs/heads/master' && 'dev' || '' }}
          label-custom: |
            org.opencontainers.image.vendor=zwave-js
            org.opencontainers.image.documentation=https://zwave-js.github.io/zwavejs2mqtt/#/
            org.opencontainers.image.authors=Daniel Lando <daniel.sorridi@gmail.com>
            org.opencontainers.image.url=https://zwave-js.github.io/zwavejs2mqtt/#/
            maintainer=robertsLando
      # - id: cache_docker_layers
      #   name: Cache Docker layers
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: buildx-${{ github.ref }}-${{ github.sha }}
      #     restore-keys: |
      #       buildx-${{ github.ref }}-${{ github.sha }}
      #       buildx-${{ github.ref }}
      #       buildx-
      - id: prepare_env
        name: Prepare environment
        run: |
          # Show important env variables:
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
          echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
          # Get branch name:
          case "${GITHUB_REF}" in
            refs/pull/*/merge)
              z2m_tagname="${GITHUB_HEAD_REF}"
            ;;
            refs/heads/*)
              z2m_tagname="${GITHUB_REF##*/}"
            ;;
          esac
          echo "z2m_tagname=${z2m_tagname}" | tee -a $GITHUB_ENV
          # Check, if dependencies have changed:
          if git diff --name-only ${GITHUB_SHA} | grep -q -E '^package(-lock)?\.json$'; then
            z2m_deps_changed=true
            echo "z2m_deps_changed=${z2m_deps_changed}" | tee -a $GITHUB_ENV
          fi
          # Check, if base images exist:
          if ! docker images -q zwavejs/zwavejs2mqtt-builder-base:${z2m_tagname} | grep -E -q '.+'; then
            echo "z2m_build_builder_base=true" | tee -a $GITHUB_ENV || true
          elif [ "${z2m_deps_changed}" ]; then
            echo "z2m_build_builder_base=true" | tee -a $GITHUB_ENV || true
          fi
          if ! docker images -q zwavejs/zwavejs2mqtt-runtime-base:${z2m_tagname} | grep -E -q '.+'; then
            echo "z2m_build_runtime_base=true" | tee -a $GITHUB_ENV || true
          elif [ "${z2m_deps_changed}" ]; then
            echo "z2m_build_runtime_base=true" | tee -a $GITHUB_ENV || true
          fi
      - id: docker_builder_base_image
        name: Build docker builder base image
        uses: docker/build-push-action@v2
        if: ${{ env.z2m_build_builder_base }}
        with:
          # platforms: linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7
          platforms: linux/amd64
          file: docker/Dockerfile.builder-base
          # cache-from: type=local,mode=max,src=/tmp/.buildx-cache
          # cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          build-args:
            | # TODO: Adjust tags to allow different for PRs + branches
            NODE_IMAGE_TAG=12.20.1-alpine
          push: true # TODO: Remove again - just temporary for testing
          tags: zwavejs/zwavejs2mqtt-builder-base:${{ env.z2m_tagname }}
      - id: docker_runtime_base_image
        name: Build docker runtime base image
        uses: docker/build-push-action@v2
        if: ${{ env.z2m_build_runtime_base }}
        with:
          # platforms: linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7
          platforms: linux/amd64
          file: docker/Dockerfile.runtime-base
          # cache-from: type=local,mode=max,src=/tmp/.buildx-cache
          # cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          build-args:
            | # TODO: Adjust tags to allow different for PRs + branches
            NODE_IMAGE_TAG=12.20.1-alpine
          push: true # TODO: Remove again - just temporary for testing
          tags: zwavejs/zwavejs2mqtt-runtime-base:${{ env.z2m_tagname }}
      - id: docker_builder_image
        name: Build docker builder image
        uses: docker/build-push-action@v2
        with:
          # platforms: linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7
          platforms: linux/amd64
          file: docker/Dockerfile.builder
          # cache-from: type=local,mode=max,src=/tmp/.buildx-cache
          # cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          build-args:
            | # TODO: Adjust tags to allow different for PRs + branches
            BUILDER_BASE_IMAGE_TAG=${{ env.z2m_tagname }}
            NODE_IMAGE_TAG=12.20.1-alpine
          push: true # TODO: Remove again - just temporary for testing
          tags: zwavejs/zwavejs2mqtt-builder:${{ env.z2m_tagname }}
      - id: docker_runtime_image
        name: Build docker runtime image
        uses: docker/build-push-action@v2
        with:
          # platforms: linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7
          platforms: linux/amd64
          file: docker/Dockerfile.runtime
          # cache-from: type=local,mode=max,src=/tmp/.buildx-cache
          # cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          build-args:
            | # TODO: Adjust tags to allow different for PRs + branches
            BUILDER_IMAGE_TAG=${{ env.z2m_tagname }}
            RUNTIME_BASE_IMAGE_TAG=${{ env.z2m_tagname }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
