name: Docker Build

on:
  push:
    branches:
      - master
    paths:
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
  release:
    types:
      - created

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Login to dockerhub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: build_base_images
        name: Build docker base images
        if: ${{ false }}
        run: docker-compose -f docker/docker-compose.build.yml build zwavejs2mqtt-build-base zwavejs2mqtt-runtime-base
      - id: build_final_image
        name: Build final docker image
        run: docker-compose -f docker/docker-compose.build.yml build zwavejs2mqtt-build zwavejs2mqtt-runtime
